### ISSUE TITLE
Add "All News" Link to Frontpage

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#138]
![gemeinde_ruti_zh](https://cloud.githubusercontent.com/assets/186856/11893028/86d60daa-a56d-11e5-9cfa-ee84f678489e.jpg)

**Comment by freinhard** [comment]
Requested by Rüti: showing more then 2 news on the frontage listing. Is this a good idea?

**Comment by href** [comment]
Well we would have add pagination then, which I feel is not a good idea. It would look weird and be confusing. Not to mention that the more news stories they have on the page, the less likely people are to read any of them. Though I could live with having three news items there. 

I also wouldn't add a "all news" link below those stories because I don't feel it belongs there. We have an all news link with "Aktuelles" already.

Since the current all news link is hard to discover however we might want to improve that like this:
![screenshot of safari 18-12-15 10-07-28](https://cloud.githubusercontent.com/assets/273163/11893266/73611b64-a56f-11e5-9230-a830df1efdb1.png)

Note the news years added below "Aktuelles".
This would make this easy to discover.

**Comment by href** [comment]
This would also balance things out, because currently there are no links below "Aktuelles" and we can't add news stories there because they tend to have wide titles.

**Comment by freinhard** [comment]
+1

**Comment by href** [comment]
Cool. This gives us the change to add a by-year view to the news overview. So if you end up on the news page you can jump to one of the existing years.
