### ISSUE TITLE
Date Format Calendar Title

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#141]
> Dann haben wir gleich noch etwas gesehen, bei der Waldhütte kommt die Woche mit 21 – 27. Dez. 2015 bei der vorderen Zahl müsste noch ein Punkt hin. Also wir Frauen würden meinen es müsste heissen 21. – 27. Dez. 2015. Könnten Sie dies bitte noch anpassen?

![calendar](https://cloud.githubusercontent.com/assets/186856/11950373/19c46662-a888-11e5-8914-b9603725958a.png)

**Comment by freinhard** [comment]
I'm not sure about this...

**Comment by href** [comment]
I tend to agree with this, but it seems difficult to change because it's not just a simple format specification. So we need to write our own date rendering function and override the default.

For me this is too large a change just to add a dot.

The default rendering is probably there for a reason and the more we touch it, the more problems we'll have in the future as the fullcalendar.js progresses.

**Comment by href** [comment]
I don't think there's a point in actually doing this.
