### ISSUE TITLE
Reaction & Lead Time

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#207]
- Lead time is the total time that elapses from the creation of a task until its completion. 
- Reaction time is the time that elapses from the creation of a task until the work is started.

http://www.screenful.me/lead-time/

"Kanban in der Gemeindeverwaltung" :)

**Comment by href** [comment]
I really ought to start a career in software process management. No need to be precise about things.

Reaction time is defined clearly enough, but lead time and/or cycle time is really not. There are a number of contradictory definitions out there. So we should find out what it is exactly that we want to measure.

Because one definition of lead time is easy: The difference between ticket creation and ticket completion. Another definition adds some complexity though. This one defines lead time as reaction time plus cycle time. This however is *not* the same as the time between creation and completion. Depending on who you ask of course, because cycle time is defined in various ways.

So we want "lead time" to either be:

* The time it took between ticket creation and ticket completion.
* The time during which a ticket was pending.

This again sounds roughly equivalent, but it's really not. The time between creation and completion can change *a lot* if we reopen a ticket after a while. The time during which a ticket was pending however only accounts for the time a ticket was being worked on.

I lean towards the second option as it tells us more about how much work a ticket took (for instance, we can figure out which forms take the most work). However I'm not sure if this is the right thing to measure for Kanban purposes (but then again, it hardly matters with this pseudo science).

I suggest therefore not to implement lead time, but process/flow time, which seems to be defined clearly enough:

http://tameflow.tendon.net/post/56252147592/replacing-cycle-time-with-flow-time

I prefer the name "process time", basically the time actually spent on a ticket.

**Comment by href** [comment]
This has been implemented in the last release.
