### ISSUE TITLE
Group Images by (Natural) Date Ranges

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.town#26]
Might be a good reason to add ORM support (see https://github.com/OneGov/onegov.town/commit/0567568f45f5be801b31a3f17d4578e18b927696) ;)

**Comment by href** [comment]
Now that's what I would call a premature optimization ;)

I'd like to avoid ORM support because without it we gain the ability to move and serve all our files to S3 on a whim, with a simple config change. See http://docs.pyfilesystem.org/en/latest/

ORM support would also mean adding transaction support. Because the file mustn't be stored if the transaction fails. Another package did that and it doesn't look too simple tbh:

https://github.com/amol-/depot/blob/master/depot/fields/sqlalchemy.py

**Comment by treinhard** [comment]
repoze.filesafe (http://docs.repoze.org/filesafe) adds transaction support for regular files. Not sure how easily that can be done with other backends like S3 though.

**Comment by msom** [comment]
The image grouping uses now only one iteration over all files, should be ok...

**Comment by href** [comment]
Is this solved or do we need to keep this ticket open?
