### ISSUE TITLE
Embed Video to Page

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#46]
Via the Redactor text editor

<img width="1392" alt="video" src="https://cloud.githubusercontent.com/assets/186856/9380909/9b911836-4733-11e5-9b04-d05bd23c6b98.png">

**Comment by href** [comment]
Turns out this is a real pita to get right. The iframe causes rendering issues, using videos in the editor is cumbersome and we basically have flash running on our site.

Maybe there's a better way.. In any case I don't want to do the insert video thing. I would prefer we link to a video instead. Maybe I can detect links to youtube and make them into videos, which would be easier to handle.

Or maybe we find a way to host our own or have someone host it for us in a sane way. That means html5 video, which is way better.

**Comment by href** [comment]
Using a javascript to scan the post content for youtube videos when the site is viewed might be interesting. We would detect all video links and dynamically replace them with iframes. Or we  show a little icon next to the video link that loads the video when it is clicked.

**Comment by href** [comment]
This: http://ctrlq.org/code/19452-embed-youtube-with-javascript
http://www.labnol.org/internet/light-youtube-embeds/27941/

Show a thumbnail for the video, load it on click! We'll have to see how well that works out, but it's a nice approach.

**Comment by href** [comment]
I suggest we simply mark youtube/vimeo links in the backend with the 'video' class and then use javascript to load the classes marked so in the browser.

**Comment by href** [comment]
This has been implemented with https://github.com/OneGov/onegov.town/compare/a98efc54d054e938d1a5726a420aab4b1ff63b68...5b07b9ed79cb78d39c6e162e7f6b33e897e7141e

This is how it works:

* Users add a youtube or a vimeo link in the editor (must be an actual link, not just text)
* Users save the page
* When the page is opened, a javascript turns the links into embedded content

Theoretically this has certain risks. We need to trust both Youtube and Vimeo not to serve us clickjacking code. I was close to not implementing iframes and using a thumbnail with a link to a new window instead, but I decided that I was being overly paranoid.

Generally we should tell people to use Vimeo if they ask, as it looks better and allows us to actually set the controls to the primary color, which is nice. Not to mention that Youtube has ads, so towns using Youtube should be aware that they can have ads running on their sites like this.
