### ISSUE TITLE
More Information for Person in Directory

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#47]
Additional information such as day in the office or deputy. Maybe just a free text field "remarks".

**Comment by freinhard** [comment]
How to add a second phone number?

**Comment by href** [comment]
There are basically three possible approaches:

* Add another custom syntax where we have a field like this, which we parse:
  
  ```
  Office Days = Monday-Friday
  Phone Number 2 = 1234567
  ```

  Since this doesn't fit in anywhere else, this is probably rubbish.

* Add the ability to define the person fields similar to the custom forms.

  This is pretty complicated to implement. With reservations and forms we are dealing with submissions. So each submission can have it's own form definition, so we never have to worry about form definition changes. Here we do, because the form definition might change for existing records.

* Have a simple "Notes" field.
  
  This would be very easy to implement, but we won't be able to reuse that information anywhere. That is especially bad if we suddenly have to add some kind of export.

I do think we should start as simple as possible, so I propose we implement a simple notes field, without formatting, but with link parsing. We show that field a bit apart from the rest and maybe style it somewhat differently, to emphasize that the notes and the rest of the fields are different.

If we do have to do something with the data in these fields we can still ask people to either write their notes in a simple `Label: Value` style or by adding something nifty to the WYSIWYG editor.

**Comment by freinhard** [comment]
+1 for the free text notes field.
