### ISSUE TITLE
Allow Editors to Define a Sort Order for Pages Different from A-Z

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#83]
User should have the option to sort pages manually. This would overrule the A-Z sorting for the page and its siblings.

Defining a sort order is done via the edit bar of a page by using a 'up' / 'down' button. Also there should be a clear indication that a manual sort order (different from A-Z) is defined and a way to reset the default sorting for a page level.

A-Z icon: http://fortawesome.github.io/Font-Awesome/icon/sort-alpha-asc/

**Comment by href** [comment]
That seems more complicated and less transparent. What you are describing is an automatic and a manual sort *mode*. Modes are always bad for usability because the user has to know which mode he is using (and we have to indicate it).

Instead we should, if we go on with this:

* Add all new pages to the bottom of the pile.
* Provide a way to move around single pages.
* Add a way to sort all children a-z by the click of a button (one-time sort)

There is no half-assed way to do this. Either we do sort everything by A-Z and enforce it. Or we simply stop caring and leave this to the user. If we do go on with this I would suggest that we use the big-lettered A-Z thing for all pages which do enforce A-Z. Otherwise we might have to do the same thing for forms and people.

**Comment by href** [comment]
I'm also not too sure the button up/down is a good option if we want to offer A-Z as a button. Maybe doing this with Javascript in the sidebar would be a more user-friendly option.

**Comment by freinhard** [comment]
https://rueti.onegovcloud.ch/themen/politik-verwaltung/news-mitteilungen/beschlusse/2015
![image001](https://cloud.githubusercontent.com/assets/186856/10520702/dde93b96-736b-11e5-8030-374e9d7f971b.png)

**Comment by href** [comment]
I'm pretty convinced this is the way to solve this:

- [ ] Add the ability to reorder pages (parents/children) using drag & drop in the side bar
- [ ] Add new pages to the bottom

I won't be doing A-Z as a button just now, because we know don't have any guarantees about the order of the pages so we might as well have them manually sorted. We don't want the user to get the impression that A-Z is the norm when it won't be.

**Comment by freinhard** [comment]
I'm not yet convinced. I still believe that A-Z is best for most cases.

**Comment by href** [comment]
Only if we can enforce it, which we can't.

**Comment by href** [comment]
It's an either/or decision.

**Comment by href** [comment]
Final plan after discussion:

- [] Pages are always sorted by the internal sort id
- [] Users may move the pages around by drag&drop in the sidebar navigation
- [] By default, pages are added in A-Z order
- [] If the order is no longer A-Z the pages are added at the bottom
