### ISSUE TITLE
Change Subtitle Below Reservations on Frontpage

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.town#87]
Tageskarten und Räume

Replace "Tageskarten" with "Standorte"

**Comment by href** [comment]
As discussed, we show the actual content of the reservations. If there *are* any daypasses, we show "Tageskarten und Räume", if there are only daypasses we show "Tageskarten", if there are only rooms we show "Räume". This gives us the ability to add other types in the future while remaining consistent.

**Comment by freinhard** [comment]
Split the two views? One for for rooms and one for day passes.

**Comment by href** [comment]
-1, that would be a lot of work

**Comment by href** [comment]
a lot more work than changing a label that is

**Comment by href** [comment]
Because there are more options and special cases than just a number of different types present in the database (we have hidden, but existing types for example). It's now possible to simply override the default using the settings:

![screenshot of google chrome 06-11-15 15-19-13](https://cloud.githubusercontent.com/assets/273163/10999025/f58bda3a-8499-11e5-9f8a-22fbc96de817.png)
